# docker-compose.production.yml
version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "${PORT:-3002}:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000    # Explicitly set container port
    restart: always
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-1}'
          memory: '${MEMORY_LIMIT:-1G}'
    depends_on:
      - db
    networks:
      - app-network-prod

  db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27019}:27017"
    volumes:
      - mongodb_data_prod:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME:-anonymous-sharing-prod}
    healthcheck:
      disable: true
    networks:
      - app-network-prod

volumes:
  mongodb_data_prod:
    name: ${COMPOSE_PROJECT_NAME:-anonymous-sharing-prod}_mongodb_data

networks:
  app-network-prod:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME:-anonymous-sharing-prod}-network