# docker-compose.staging.yml
version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: staging
    ports:
      - "${PORT:-3001}:3000"
    env_file:
      - .env.staging
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
    networks:
      - app-network-staging

  db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27018}:27017"
    volumes:
      - mongodb_data_staging:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network-staging

volumes:
  mongodb_data_staging:
    name: ${COMPOSE_PROJECT_NAME:-anonymous-sharing-staging}_mongodb_data

networks:
  app-network-staging:
    name: ${COMPOSE_PROJECT_NAME:-anonymous-sharing-staging}_network
    driver: bridge