# docker-compose.production.yml
version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
    networks:
      - app-network-prod

  db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data_prod:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network-prod

volumes:
  mongodb_data_prod:
    name: ${COMPOSE_PROJECT_NAME:-anonymous-sharing-prod}_mongodb_data

networks:
  app-network-prod:
    name: ${COMPOSE_PROJECT_NAME:-anonymous-sharing-prod}_network
    driver: bridge