name: CI/CD Staging Pipeline

on:
  push:
    branches:
      - develop
    tags:
      - "v*-rc*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
      lowercase_repo: ${{ steps.repo_name.outputs.LOWERCASE_REPO }}
    steps:
      - uses: actions/checkout@v3

      - name: Get the version (for tags or develop)
        id: get_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=develop" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo_name
        run: |
          echo "LOWERCASE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.LOWERCASE_REPO }}:${{ env.TAG }}
            ghcr.io/${{ env.LOWERCASE_REPO }}:staging
          no-cache: true

  deploy-staging:
    needs: build-and-push
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            set -e  # Exit immediately if any command fails

            echo "Logging into GitHub Container Registry..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Setting environment variables..."
            export GITHUB_REPOSITORY="${{ env.LOWERCASE_REPO }}"
            export TAG="${{ env.TAG }}"

            echo "Deploying application..."
            REPO_DIR="anonymous-sharing"
            if [ -d "$REPO_DIR" ]; then
              cd "$REPO_DIR"
              git fetch --all
              git checkout ${TAG}
            else
              git clone --branch ${TAG} https://${{ secrets.GH_PAT }}@github.com/${GITHUB_REPOSITORY}.git "$REPO_DIR"
              cd "$REPO_DIR"
            fi

            echo "Updating .env.staging with secrets..."
            sed -i "s|MONGO_USER=.*|MONGO_USER=${{ secrets.STAGING_MONGO_USER }}|" .env.staging
            sed -i "s|MONGO_PASSWORD=.*|MONGO_PASSWORD=${{ secrets.STAGING_MONGO_PASSWORD }}|" .env.staging
            sed -i "s|MONGODB_URI=.*|MONGODB_URI=${{ secrets.STAGING_MONGODB_URI }}|" .env.staging

            echo "Stopping existing containers..."
            docker-compose -f docker-compose.staging.yml down

            echo "Pulling latest images..."
            TAG=${TAG} docker-compose -f docker-compose.staging.yml pull

            echo "Starting services..."
            TAG=${TAG} docker-compose -f docker-compose.staging.yml --env-file .env.staging up -d --build

            echo "Cleaning up..."
            docker image prune -f

            echo "Deployment complete!"
